# How to run it:
#   docker-compose up -d
#
# How to stop it:
#   docker-compose down

version: "3.9"

services:

  db:
    image: mysql:8
    container_name: reviews
    environment:
      MYSQL_ROOT_PASSWORD: Propato
    volumes:
      - ./DDS:/docker-entrypoint-initdb.d
      - ./functions:/functions
      - db_data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  db_data: